import "../css/header.css";
import "../css/common.css";
import "../css/countdown.css";
import "../css/glossary.css";
import "../css/exam-college-bba-lp.css";
import "../css/faq.css";
import "../css/footer.css";
import "./course.js";
import "./faq.js";
